### ISSUE TITLE
shipping page not showing

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Internal---Liz-Store-dev.---31-May-2022#13]
Bug - shipping page not linked with respective page.
Exp - On clicking shipping policy page should get redirect to shipping policy page.
Ref Link - https://drive.google.com/file/d/1yekD68SHOYgfekE7SeNGCISZtDRDXorL/view

**Comment by devabulabbas** [comment]
Resolved

**Comment by ankitcedcoss** [comment]
Bug Fixed
